--UPDATE VEM_SER.ENDERECO e
--SET  e.LOGRADOURO = 'rua torta', e.COMPLEMENTO = 'bloco 89'
--WHERE e.ID_ENDERECO = 2;
--
--UPDATE VEM_SER.ENDERECO e
--SET  e.LOGRADOURO = 'rua reta', e.COMPLEMENTO = 'torre B'
--WHERE e.ID_ENDERECO = 3;

UPDATE VEM_SER.ENDERECO e 
SET 
	e.LOGRADOURO = CASE 
						WHEN e.ID_ENDERECO = 2 THEN 'Rua torta'
						WHEN e.ID_ENDERECO = 3 THEN 'Rua reta'
				   END,
    e.COMPLEMENTO = CASE 
						WHEN e.ID_ENDERECO = 2 THEN 'Bloco 89'
						WHEN e.ID_ENDERECO = 3 THEN 'Torre B'
					END
WHERE e.ID_ENDERECO IN (2,3);
	
UPDATE VEM_SER.ENDERECO e
SET  e.NUMERO = 999999
WHERE e.ID_ENDERECO = 4;

DELETE FROM VEM_SER.ENDERECO
WHERE ID_ENDERECO = (SELECT MAX(ID_ENDERECO) FROM VEM_SER.ENDERECO);

DELETE FROM VEM_SER.ENDERECO e
WHERE e.NUMERO = 999999;

DELETE FROM VEM_SER.ENDERECO e 
WHERE e.ID_ENDERECO IN (10, 20);


