
--fazer cross join entre Pessoa e contato
SELECT * 
FROM VEM_SER.PESSOA p 
CROSS JOIN VEM_SER.CONTATO c;

--fazer inner join entre Pessoa e contato
SELECT *
FROM VEM_SER.PESSOA p 
INNER JOIN CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;

--fazer inner entre Pessoa, PESSOA_XPESSOA_ENDERECO e Endereco_Pessoa
SELECT * 
FROM VEM_SER.PESSOA p 
INNER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA
INNER JOIN VEM_SER.ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO  = ep.ID_ENDERECO ;

--fazer inner entre todas as tabelas começando por pessoa
SELECT * 
FROM VEM_SER.PESSOA p 
INNER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA
INNER JOIN VEM_SER.ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO  = ep.ID_ENDERECO
INNER JOIN VEM_SER.CONTATO c  ON p.ID_PESSOA  = c.ID_PESSOA;

-- fazer left join entre Pessoa e contato
--sera null quando nao houver correspondencia
SELECT *
FROM VEM_SER.PESSOA p 
LEFT JOIN VEM_SER.CONTATO c ON p.ID_PESSOA = c.ID_CONTATO;

-- fazer left entre pessoa,PESSOA_XPESSOA_ENDERECO e Endereco_Pessoa
SELECT * 
FROM VEM_SER.PESSOA p 
LEFT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA 
LEFT JOIN VEM_SER.ENDERECO_PESSOA ep ON ep.ID_ENDERECO  = pxpe.ID_ENDERECO;

-- fazer left  entre todas as tabelas começando por pessoa
SELECT *
FROM VEM_SER.PESSOA p 
LEFT JOIN VEM_SER.CONTATO c ON p.ID_PESSOA = c.ID_PESSOA 
LEFT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA 
LEFT JOIN VEM_SER.ENDERECO_PESSOA ep ON ep.ID_ENDERECO  = pxpe.ID_ENDERECO


SELECT * FROM VEM_SER.PESSOA P
INNER JOIN VEM_SER.CONTATO C ON P.ID_PESSOA = C.ID_PESSOA
INNER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PPE ON P.ID_PESSOA = PPE.ID_PESSOA
INNER JOIN VEM_SER.ENDERECO_PESSOA E on PPE.ID_ENDERECO = E.ID_ENDERECO;

