--RIGHT JOIN entre:
--Pessoa e Contato
SELECT * 
FROM VEM_SER.PESSOA p 
RIGHT JOIN VEM_SER.CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;

--Pessoa, PESSOA_X_PESSOA_ENDERECO e Endereco_PESSOA
SELECT * 
FROM VEM_SER.PESSOA p 
RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA 
RIGHT JOIN VEM_SER.ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

--TODAS AS TABELAS começando por Pessoa
SELECT * 
FROM VEM_SER.PESSOA p 
RIGHT JOIN VEM_SER.CONTATO c ON p.ID_PESSOA = c.ID_PESSOA
RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA 
RIGHT JOIN VEM_SER.ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO

--FULL JOIN entre:
--Pessoa e Contato
SELECT * 
FROM VEM_SER.PESSOA p 
FULL JOIN VEM_SER.CONTATO c ON p.ID_PESSOA = c.ID_PESSOA ;

--Pessoa, PESSOA_X_PESSOA_ENDERECO e Endereco_PESSOA
SELECT * 
FROM VEM_SER.PESSOA p 
FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA
FULL JOIN VEM_SER.ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

--TODAS AS TABELAS começando por Pessoa
SELECT * 
FROM VEM_SER.PESSOA p 
FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA
FULL JOIN VEM_SER.ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO
FULL JOIN VEM_SER.CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;

--Utilizando EXISTS, selecione as pessoas que tem um endereço
SELECT *
FROM VEM_SER.PESSOA p 
WHERE EXISTS (SELECT *
			  FROM PESSOA_X_PESSOA_ENDERECO pxpe 
			  WHERE pxpe.ID_PESSOA = p.ID_PESSOA
			 );

--Selecione id, nome da tabela pessoa junto com id, logradouro da tabela endereço		
SELECT p.id_pessoa, p.nome FROM PESSOA p
UNION
SELECT ep.id_endereco, ep.logradouro FROM ENDERECO_PESSOA ep;
			
