
SELECT * FROM VEM_SER.PAIS p 
ORDER BY NOME DESC;

SELECT logradouro, cep FROM VEM_SER.ENDERECO
WHERE UPPER(logradouro) LIKE 'A%';

SELECT * FROM VEM_SER.ENDERECO e 
WHERE e.CEP LIKE '%0';

SELECT * FROM VEM_SER.ENDERECO e 
WHERE e.NUMERO BETWEEN 1 AND 100;

SELECT * FROM VEM_SER.ENDERECO e 
WHERE UPPER(e.LOGRADOURO) LIKE 'RUA%'
ORDER BY e.cep DESC;

SELECT COUNT(*) AS qtd_enderecos FROM VEM_SER.ENDERECO;

SELECT COUNT(*) AS qtd_enderecos FROM VEM_SER.ENDERECO e
GROUP BY e.ID_CIDADE ;
